final project sprint#4
Dostoebski/Sprint_4 pull request #1
Opened 2022-07-10 18:27 UTC by Dostoebski

2022-07-11 15:13 UTC, nrasskosova requested changes

2022-07-11 15:13 UTC, nrasskosova commented on src/test/java/ru/yandex/praktikum/FAQOnMainPageTest.java
> +    public void answerTextOnFirstQuestionTest() {
У тебя одни и т же шаги повторяются в каждом тесте. Общую часть надо вынести в @Before метод, а в тестах оставить шаги, которые уникальны для каждого теста

2022-07-11 15:13 UTC, nrasskosova commented on src/test/java/ru/yandex/praktikum/TestTemplate.java
> +    public void TearDown() {
нужно поправить название метода согласно camelCase

2022-07-11 15:13 UTC, nrasskosova commented on src/test/java/ru/yandex/praktikum/TestTemplate.java
> +    @Before
Этот метод можно сделать @BeforeClass, чтобы настройка производилась перед запуском тестового класса, а не перед каждым тестом.

2022-07-11 15:13 UTC, nrasskosova commented on src/test/java/ru/yandex/praktikum/TestTemplate.java
> +    @After
аналогично этот метод можно запускать после прогона всего тестового класса. Иначе браузер у тебя будет закрываться после каждого теста

2022-07-11 15:13 UTC, nrasskosova commented on src/test/java/ru/yandex/praktikum/ScooterOrderCreatedTest.java
> +    public void ScooterOrderFromUpperButtonTest() {
вынеси общие щаги в @After метод в этом классе

2022-07-12 06:44 UTC, nrasskosova requested changes

2022-07-12 06:44 UTC, nrasskosova commented on src/test/java/ru/yandex/praktikum/FAQOnMainPageTest.java
> +    // Проверка первого вопроса
вот эту комментарии можно указывать в @DisplayName

2022-07-12 06:44 UTC, nrasskosova commented on src/test/java/ru/yandex/praktikum/ScooterOrderCreatedTest.java
> +    public void ScooterOrderFromUpperButtonTest() {
нужно поправить название этого метода согласно camelCase

2022-07-12 06:44 UTC, nrasskosova commented on src/test/java/ru/yandex/praktikum/ScooterOrderCreatedTest.java
> +    public void ScooterOrderFromLowerButtonTest() {
нужно поправить название этого метода(со строчной буквы первое слово)

2022-07-12 13:30 UTC, Dostoebski commented on src/test/java/ru/yandex/praktikum/FAQOnMainPageTest.java
> +    // Проверка первого вопроса
Насколько понял, DisplayName есть только в junit 5. Не стал менять версию.

2022-07-13 15:53 UTC, merged